ARG DISTROLESS_IMAGE="quay.io/quarkus/quarkus-distroless-image:2.0-2026-02-22@sha256:36359d587f6ddabd30f822696a61bf9ad80dd39adb5ba18a91fd04a1eec4369b"

FROM ${DISTROLESS_IMAGE} AS runner
ARG APP_DIR=/deployment
ARG UID=1001

USER root
WORKDIR ${APP_DIR}
# Include if the project has .so that need to be copied:
# COPY \
#  --chmod=444 \
#  target/*.so /lib/
COPY \
  --chmod=111 \
   target/*-runner ${APP_DIR}/application

ENV LANGUAGE='en_US:en'
USER ${UID}:${UID}
ENTRYPOINT [ "./application" ]
