quarkus.application.name = quarkus-workshop

quarkus.amqp.devservices.image-name = quay.io/arkmq-org/activemq-artemis-broker:artemis.2.52.0

quarkus.otel.logs.enabled = true
quarkus.otel.metrics.enabled = true
quarkus.otel.traces.enabled = true

mp.messaging.outgoing.user-send.connector = smallrye-amqp
mp.messaging.outgoing.user-send.address = user
mp.messaging.outgoing.user-send.container-id = ${quarkus.application.name}-user-writer

mp.messaging.incoming.user-receive.connector = smallrye-amqp
mp.messaging.incoming.user-receive.address = user::quarkus-workshop-reader
mp.messaging.incoming.user-receive.durable = true
mp.messaging.incoming.user-receive.container-id = ${quarkus.application.name}-user-reader

%dev.quarkus.http.access-log.enabled = true